// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-2jIo3cAT-qg7DXVOkdnFcG09s48B1dM',
    appId: '1:465980712733:web:c2dad911c7aefa3a6d23f4',
    messagingSenderId: '465980712733',
    projectId: 'spendscontrol',
    authDomain: 'spendscontrol.firebaseapp.com',
    storageBucket: 'spendscontrol.firebasestorage.app',
    measurementId: 'G-9XB6F6P4DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuqX2KJ9i6Lq8S_3fSIK2h5RPMJaVMQ50',
    appId: '1:465980712733:android:c7f9c3383eeb3aeb6d23f4',
    messagingSenderId: '465980712733',
    projectId: 'spendscontrol',
    storageBucket: 'spendscontrol.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaFfr0AfsO4lS1KJ2xQ86JvY8hEGI40HY',
    appId: '1:465980712733:ios:4767b1d1e56753236d23f4',
    messagingSenderId: '465980712733',
    projectId: 'spendscontrol',
    storageBucket: 'spendscontrol.firebasestorage.app',
    iosBundleId: 'com.example.spendscontrol',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaFfr0AfsO4lS1KJ2xQ86JvY8hEGI40HY',
    appId: '1:465980712733:ios:4767b1d1e56753236d23f4',
    messagingSenderId: '465980712733',
    projectId: 'spendscontrol',
    storageBucket: 'spendscontrol.firebasestorage.app',
    iosBundleId: 'com.example.spendscontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-2jIo3cAT-qg7DXVOkdnFcG09s48B1dM',
    appId: '1:465980712733:web:6cc14257c8b7a0456d23f4',
    messagingSenderId: '465980712733',
    projectId: 'spendscontrol',
    authDomain: 'spendscontrol.firebaseapp.com',
    storageBucket: 'spendscontrol.firebasestorage.app',
    measurementId: 'G-GRKTEZ9G0N',
  );
}
